=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Printing Errors:
Custom Error
Traceback (most recent call last):
  File "G:\Ayman_APP\Fortran\Cycle2Py_NewDesgin\Class_Compressor\ErrorException_Test.py", line 11, in <module>
    list_check([1, 3, 5])
  File "G:\Ayman_APP\Fortran\Cycle2Py_NewDesgin\Class_Compressor\ErrorException_Test.py", line 5, in list_check
    raise ErrorException('Custom Message', 'Custom Error')
ErrorException.ErrorException: Custom Message
